-- Initialize teamDB with values
INSERT INTO gamedb.team (name) VALUES
	 ('milan'),
	 ('roma'),
	 ('catania'),
	 ('palermo'),
	 ('juventus'),
	 ('napoli'),
	 ('torino'),
	 ('genoa'),
	 ('bologna'),
	 ('sassuolo'),
	 ('sampdoria'),
	 ('cagliari'),
	 ('atalanta'),
	 ('udinese'),
	 ('fiorentina'),
	 ('chievo'),
	 ('spal'),
	 ('siena'),
	 ('lazio'),
	 ('inter');